import pants1 from '../../assets/pants1.png';
import pants2 from '../../assets/pants2.png';
import pants3 from '../../assets/pants3.png';
import shirt1 from '../../assets/shirt1.png';
import shirt2 from '../../assets/shirt2.png';
import tShirt1 from '../../assets/t-shirt1.png';
import tShirt2 from '../../assets/t-shirt2.png';
import tShirt3 from '../../assets/t-shirt3.png';
import tShirt4 from '../../assets/t-shirt4.png';
import tShirt5 from '../../assets/t-shirt5.png';
import tShirt6 from '../../assets/t-shirt6.png';
import tShirt7 from '../../assets/t-shirt7.png';

const initialState = {
  allProduct: [
    {
      id: 1,
      image: pants1,
      title: 'FADED SKINNY JEANS',
      raiting: 4.5,
      price: 210,
      category: 'pants',
      sale: null,
      saleProcent: null,
      color: 'black',
      size: 'large',
      style: 'casual',
    },
    {
      id: 2,
      image: pants2,
      title: 'SKINNY FIT JEANS',
      raiting: 3.5,
      price: 240,
      sale: 260,
      saleProcent: '-20%',
      category: 'pants',
      color: 'blue',
      size: 'xLarge',
      style: 'formal',
    },
    {
      id: 3,
      image: pants3,
      title: 'LOOSE FIT BERMUDA SHORTS',
      raiting: 3,
      price: 80,
      sale: null,
      saleProcent: null,
      category: 'pants',
      color: 'skyBlue',
      size: 'small',
      style: 'party',
    },
    {
      id: 4,
      image: shirt1,
      title: 'CHECKERED SHIRT',
      raiting: 4.5,
      price: 180,
      sale: null,
      saleProcent: null,
      category: 'shirt',
      color: 'purple',
      size: 'medium',
      style: 'casual',
    },
    {
      id: 5,
      image: shirt2,
      title: 'VERTICAL STRIPED SHIRT',
      raiting: 5,
      price: 212,
      sale: 232,
      saleProcent: '-20%',
      category: 'shirt',
      color: 'green',
      size: 'xxLarge',
      style: 'formal',
    },
    {
      id: 6,
      image: tShirt1,
      title: 'Gradient Graphic T-shirt',
      raiting: 3.5,
      price: 145,
      sale: null,
      saleProcent: null,
      category: 'tShirt',
      color: 'white',
      size: '3xLarge',
      style: 'party',
    },
    {
      id: 7,
      image: tShirt2,
      title: 'Polo with Tipping Details',
      raiting: 4.5,
      price: 180,
      sale: null,
      saleProcent: null,
      category: 'tShirt',
      color: 'orange',
      size: 'xSmall',
      style: 'gym',
    },
    {
      id: 8,
      image: tShirt3,
      title: 'Black Striped T-shirt',
      raiting: 5,
      price: 120,
      sale: 150,
      saleProcent: '-30%',
      category: 'tShirt',
      color: 'white',
      size: 'xxSmall',
      style: 'gym',
    },
    {
      id: 9,
      image: tShirt4,
      title: 'T-SHIRT WITH TAPE DETAILS',
      raiting: 4.5,
      price: 120,
      sale: null,
      saleProcent: null,
      category: 'tShirt',
      color: 'black',
      size: '4xLarge',
      style: 'party',
    },
    {
      id: 10,
      image: tShirt5,
      title: 'Polo with Contrast Trims',
      raiting: 4,
      price: 212,
      sale: 242,
      saleProcent: '-20%',
      category: 'tShirt',
      color: 'blue',
      size: 'medium',
      style: 'casual',
    },
    {
      id: 11,
      image: tShirt6,
      title: 'SLEEVE STRIPED T-SHIRT',
      raiting: 4.5,
      price: 130,
      sale: 160,
      saleProcent: '-30%',
      category: 'tShirt',
      color: 'orange',
      size: 'small',
      style: 'gym',
    },
    {
      id: 12,
      image: tShirt7,
      title: 'COURAGE GRAPHIC T-SHIRT',
      raiting: 4,
      price: 145,
      sale: null,
      saleProcent: null,
      category: 'tShirt',
      color: 'orange',
      size: 'large',
      style: 'formal',
    },
  ].sort(() => 0.5 - Math.random()),
  searchQuery: '',
};

export default initialState;
